# Generated by Django 3.1 on 2020-10-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201011_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png',
                                    upload_to='profile_pics'),
        ),
    ]
