language: python

python: '3.9'

addons:
  chrome: stable

before_script:
  - wget https://chromedriver.storage.googleapis.com/89.0.4389.114/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip -d /usr/local/bin/chromedriver
  - export PATH="$PATH:/usr/local/bin/chromedriver"

services: postgresql

env: DJANGO_SETTINGS_MODULE=purbeurre.settings

script: python manage.py test
